server:
  ssl:
    #    key-store: classpath:cert/www.xxh160.com_server.jks
    key-store: classpath:cert/www.xiayi.org.cn_server.jks
    #    key-store-password: Am2#$RGYTQR^@v$n
    key-store-password: Qh6^jzF3^5xfe9&e
    key-store-type: JKS
    enabled: true
  port: 8443

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/NJUAlley?setUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: xiayi
    password: 1928yI2333!
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #druid 数据源专有配置
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 200
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 用来检测连接是否有效的sql，要求是一个查询语句
      validationQuery: SELECT 1 FROM DUAL
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testWhileIdle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnBorrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testOnReturn: false
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      poolPreparedStatements: true
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-pool-prepared-statement-per-connection-size: 50

      #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
      #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
      #则导入 log4j 依赖即可，Maven 地址：https://mvnrepository.com/artifact/log4j/log4j
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，比如不配置stat,我们在Druid的监控页面中就拿不到想要的信息。
      filters: stat,wall,log4j
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  devtools:
    restart:
      enabled: true

springfox:
  documentation:
    swagger-ui:
      enabled: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count

wechat:
  app-id: wx0a11c28291dfc29a
  app-secret: 08dbea1695755fc6f3d1791baa8315f6

oss:
  bucket-name: nju-se
  end-point: oss-cn-beijing.aliyuncs.com
  accesskey-id: LTAI5t724aEYK7wCPavU6b3A
  accesskey-secret: V4T5aWEStBa0jA5x2XD4VqgRZ3X03N
  dir: nju-alley
  callback: https://www.xiayi.org.cn:8443/api/oss/callback
  max_size: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,conditions,env