server:
  ssl:
    #    key-store: classpath:cert/www.xxh160.com_server.jks
    key-store: classpath:cert/www.xiayi.org.cn_server.jks
    #    key-store-password: Am2#$RGYTQR^@v$n
    key-store-password: Qh6^jzF3^5xfe9&e
    key-store-type: JKS
    enabled: true
  port: 8443

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/NJUAlley?setUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true

springfox:
  documentation:
    swagger-ui:
      enabled: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count

wechat:
  app-id: wx0a11c28291dfc29a
  app-secret: 08dbea1695755fc6f3d1791baa8315f6

oss:
  bucket-name: nju-se
  end-point: oss-cn-beijing.aliyuncs.com
  accesskey-id: LTAI5t724aEYK7wCPavU6b3A
  accesskey-secret: V4T5aWEStBa0jA5x2XD4VqgRZ3X03N
  dir: nju-alley
  callback: https://www.xiayi.org.cn:8443/api/oss/callback
  max_size: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,conditions,env