server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://119.23.56.136:3306/NJUAlley?setUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: xiayi
    password: 1928yI2333!
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true

springfox:
  documentation:
    swagger-ui:
      enabled: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count
