server:
  ssl:
    key-store: classpath:cert/scs1622380630476_www.xxh160.com_server.jks
    #    key-store: classpath:keystore/baeldung.p12
    key-store-password: Am2#$RGYTQR^@v$n
    key-store-type: JKS
    #    key-store-type: PKCS12
    #    key-alias: baeldung
    enabled: true
  #    key-store-password: 123456
  port: 8443

spring:
  datasource:
    url: jdbc:mysql://www.xxh160.com:3306/NJUAlley?setUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: xiayi
    password: 1928yI2333!
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true

springfox:
  documentation:
    swagger-ui:
      enabled: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count

wechat:
  app-id: wx0a11c28291dfc29a
  app-secret: 08dbea1695755fc6f3d1791baa8315f6

oss:
  bucket-name: nju-se
  end-point: oss-cn-beijing.aliyuncs.com
  accesskey-id: LTAI5t724aEYK7wCPavU6b3A
  accesskey-secret: V4T5aWEStBa0jA5x2XD4VqgRZ3X03N
  dir: nju-alley
  callback:

management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,conditions,env